/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_nana_uLCDInterface */

#ifndef _Included_com_nana_uLCDInterface
#define _Included_com_nana_uLCDInterface
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_nana_uLCDInterface
 * Method:    internalWriteImageToULCD
 * Signature: (I[[S)Z
 */
JNIEXPORT jboolean JNICALL Java_com_nana_uLCDInterface_internalWriteImageToULCD
  (JNIEnv *, jclass, jint, jobjectArray);

#ifdef __cplusplus
}
#endif
#endif
